name: demo-rojin

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
jobs:
  build:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: 'login to registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
              type=schedule
              type=semver,pattern={{version}}
              type=semver,pattern={{major}}.{{minor}}
              type=semver,pattern={{major}}
              type=ref,event=branch
              type=ref,event=pr
              type=sha
              type=semver,pattern={{version}},prefix=v
              type=raw,value=latest,enable={{is_default_branch}}

      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}

      # - id: lowercase_github_repository
      #   uses: ASzc/change-string-case-action@v2
      #   with:
      #     string: ${{ github.repository }}
      
      # - name: Build development
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: .
      #     push: true
      #     tags: ghcr.io/${{ steps.lowercase_github_repository.outputs.lowercase }}:development
      
      # - name: Build production
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: .
      #     push: true
      #     tags: ghcr.io/${{ steps.lowercase_github_repository.outputs.lowercase }}:production
